// <auto-generated />
using ApiGTT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ApiGTT.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20190212092757_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ApiGTT.Models.Certificates", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("alias");

                    b.Property<string>("contacto_renovacion");

                    b.Property<string>("entidad_emisora");

                    b.Property<string>("id_orga");

                    b.Property<string>("integration_list");

                    b.Property<string>("nombre_cliente");

                    b.Property<string>("numero_de_serie");

                    b.Property<string>("observaciones");

                    b.Property<string>("password");

                    b.Property<string>("repositorio");

                    b.Property<string>("subject");

                    b.HasKey("id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("ApiGTT.Models.Jira", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("componente");

                    b.Property<string>("password");

                    b.Property<string>("proyecto");

                    b.Property<string>("url");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Jira");
                });

            modelBuilder.Entity("ApiGTT.Models.Users", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("password");

                    b.Property<bool>("role");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
